source 'https://github.com/CocoaPods/Specs.git'

target 'MTURLBuilder', :exclusive => true do
  pod "MTURLBuilder", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MTURLBuilder", :path => "../"

  pod 'Kiwi'
end
